### ISSUE TITLE
Failed resolution of: Lcom/getkeepsafe/relinker/ReLinker;

### ISSUE THREAD

**Issue by sylendra7** [dkornev/TwilioVoiceXamarinAndroid#2]
getting the below error in xamarin android 

Failed resolution of: Lcom/getkeepsafe/relinker/ReLinker;

**Comment by dkornev** [comment]
Hey,

_Xbindings.ReLinker.Droid_ NuGet package needs to be added into your Android project.
I'll add it as a dependency later

**Comment by dkornev** [comment]
Please let me know if it fixed your issue

**Comment by sylendra7** [comment]
Thank you  it was really helped .
