### ISSUE TITLE
Can you update this to latest of Twilio?

### ISSUE THREAD

**Issue by softsan** [dkornev/TwilioVoiceXamarinAndroid#4]
Hi,

I see this is an older (around 11 month old) while on iOS binding its latest which we are currently utilizing in our app. So could you please update android also to latest of Twilio.

Thanks.

**Comment by softsan** [comment]
@dkornev Hi any updates or any ETA for this?
Thanks

**Comment by dkornev** [comment]
I'm planning to take a look at this one next week

**Comment by softsan** [comment]
Hi,
Any updates on this?

Also any plans to update iOS binding as well?

Thanks

**Comment by softsan** [comment]
Hi 
Any updates on this? Thanks

**Comment by dkornev** [comment]
Hi @softsan 
I'm really sorry but my plans had changed and I couldn't work on this one yet. I can promise nothing right now but I keep it in my head and will switch to the SDK update when I have any time.

Feel free to update the binding if you can do it.

**Comment by softsan** [comment]
Hi @dkornev  
I am able to update the latest twilio sdk 5.3.0 in your project and trying to create a PR but it gives me error:
```
Pushing to https://github.com/dkornev/TwilioVoiceXamarinAndroid.git
remote: Permission to dkornev/TwilioVoiceXamarinAndroid.git denied to softsan.
```
can you provide access of creating/ Merging  PR?
Thanks.

**Comment by dkornev** [comment]
FYI. Update to v5.4.0
